### ISSUE TITLE
incompatiable with gcc 4.8.2

### ISSUE THREAD

**Issue by zhou13** [mmp/pbrt-v2#16]
On linux, I got a segmentation fault on some serene.  This happens on `gcc-4.8.2`.  But it seems work fine on `gcc-4.7`.

```
segmentation fault  pbrt killeroo-gold.pbrt
```

**Comment by slavik81** [comment]
a7bf7eaea319f7927ceb478cd3df95545e5e1d14 is a rather frustrating solution. GCC 4.8.2 is the version used by both Ubuntu 14.04 and CentOS 7. Both distributions patched the bug, but the `#error` forces the build to fail anyways.
