### ISSUE TITLE
build issue

### ISSUE THREAD

**Issue by unicomp21** [mmp/pbrt-v2#40]
root@PBRT:~/pbrt-v2/src# make
/bin/mkdir -p bin objs
Building object objs/core_imageio.o
core/imageio.cpp:137:26: fatal error: ImfInputFile.h: No such file or directory
 #include <ImfInputFile.h>
                          ^
compilation terminated.
Makefile:115: recipe for target 'objs/core_imageio.o' failed
make: *** [objs/core_imageio.o] Error 1

**Comment by mmp** [comment]
See https://github.com/mmp/pbrt-v2/blob/master/src/README_BUILDING.txt. It looks like you don't have OpenEXR installed. If so, you need to update the Makefile.
