### ISSUE TITLE
4D noise

### ISSUE THREAD

**Issue by unicomp21** [mmp/pbrt-v2#41]
Where's the 4D noise?

**Comment by mmp** [comment]
I don't understand the question.

**Comment by unicomp21** [comment]
I see 3D noise, but no 4D noise, like OSL.

**Comment by mmp** [comment]
Then it's probably safe to assume that there isn't an implementation of 4D noise in pbrt.

**Comment by unicomp21** [comment]
Can we put this in for v3?

**Comment by Humper** [comment]
It's probably not going to make v3 (that feature set is pretty much locked
down) but we can add it for v5

**Comment by unicomp21** [comment]
Is the book still going to run $60?

**Comment by Humper** [comment]
Sorry, we're not in charge of such things.

**Comment by unicomp21** [comment]
Publisher is out of control.  Why not publish yourself so more people can
afford the book?

https://kdp.amazon.com/

**Comment by Humper** [comment]
The book is already very inexpensive
