### ISSUE TITLE
L2-Norm in exrdiff

### ISSUE THREAD

**Issue by mrecachinas** [mmp/pbrt-v2#45]
Any plan to implement L2 norm in `exrdiff`? Or any known tools out there to do that? The RMS in `exrdiff` appears to be squaring the R, G, and B distances for each pixel, averaging them across the whole image, and taking the square root, whereas the average L2-norm squares the R, G, and B distances for each pixel, takes the square root of their sum, then averages that across the whole image.

I can whip up a working implementation that could be added if you're interested.

**Comment by mmp** [comment]
Fixed in pbrt-v4's imgtool!
