### ISSUE TITLE
villa-daylight.pbrt

### ISSUE THREAD

**Issue by cslooey** [mmp/pbrt-v2#57]
Hello, when I used PBRT-V3 to render a scene witch is called "villa-daylight" in the PBRT-V2.It is said that "Warning: Parameter 'gamma' not used".How to change the scene, then we can use the PBRT-V3 to render it.Thank you so much.

**Comment by mmp** [comment]
It should be fine to ignore those warnings; that parameter changed from v2 to v3, but in this case, the default behavior in v3 should basically match v2.
